window.DB_CSV_DATA = `name,tagline,vector,graph,oss,selfhost,lightweight,docker,single,lowops,ram,persistence,server,embeddable,traversal,hybrid,rag,cypher,langs,lc,compat,url,src,notes
Qdrant,High-perf vector search engine,1,0,1,1,1,1,1,1,0,1,1,0,0,1,1,0,"Python, Go, JS, Rust",1,"Linux, macOS, Windows",https://qdrant.tech,https://github.com/qdrant/qdrant,
Chroma,AI-native open-source embedding DB,1,0,1,1,1,1,1,1,0,1,1,1,0,1,1,0,"Python, JS/TS",1,"Linux, macOS, Windows",https://trychroma.com,https://github.com/chroma-core/chroma,"{""embeddable"":""Embedded mode available; persistent-client and server modes also supported"",""persistence"":""Default in-memory mode has no persistence; use PersistentClient for durability""}"
Weaviate,AI-native vector database,1,0,1,1,0,1,1,0,0,1,1,0,0,1,1,0,"Python, Go, JS, Java",1,"Linux, macOS, Windows",https://weaviate.io,https://github.com/weaviate/weaviate,"{""oss"":""Uses Business Source License (BSL 1.1) from v1.25+ — not OSI-approved; converts to Apache 2.0 after 4 years""}"
Milvus,Cloud-native vector DB for scale,1,0,1,1,0,1,0,0,0,1,1,0,0,1,1,0,"Python, Java, Go, JS",1,"Linux, macOS, Windows",https://milvus.io,https://github.com/milvus-io/milvus,
Pinecone,Fully managed vector database,1,0,0,0,1,0,0,1,0,1,1,0,0,1,1,0,"Python, JS, Go, Java",1,Cloud (SaaS),https://pinecone.io,,"{""selfhost"":""SaaS only — no self-host option""}"
LanceDB,Serverless vector DB for AI apps,1,0,1,1,1,1,1,1,0,1,1,1,0,1,1,0,"Python, JS/TS, Rust",1,"Linux, macOS, Windows",https://lancedb.com,https://github.com/lancedb/lancedb,
pgvector,Vector similarity search for Postgres,1,0,1,1,1,1,1,1,0,1,1,0,0,1,1,0,All Postgres clients,1,"Linux, macOS, Windows",https://github.com/pgvector/pgvector,https://github.com/pgvector/pgvector,
pgvectorscale,High-perf vector search on Postgres,1,0,1,1,1,1,1,1,0,1,1,0,0,1,1,0,All Postgres clients,1,"Linux, macOS",https://github.com/timescale/pgvectorscale,https://github.com/timescale/pgvectorscale,
FAISS,Efficient similarity search library (Meta),1,0,1,1,1,1,1,1,0,0,0,1,0,0,0,0,"Python, C++",1,"Linux, macOS, Windows",https://faiss.ai,https://github.com/facebookresearch/faiss,"{""persistence"":""No built-in persistence; caller must manually save/load index files"",""server"":""Library only — no server mode; must be wrapped by the application"",""embeddable"":""In-process library with no storage engine; caller is fully responsible for saving and loading index files""}"
Elasticsearch,Distributed search & analytics engine,1,0,0,1,0,1,1,0,0,1,1,0,0,1,1,0,"Python, Java, JS, Go, Ruby",1,"Linux, macOS, Windows",https://elastic.co,https://github.com/elastic/elasticsearch,
MongoDB Atlas Vector,Document DB with vector search,1,0,0,0,0,0,0,1,0,1,1,0,0,1,1,0,"Python, JS, Java, Go, C#",1,Cloud (SaaS),https://www.mongodb.com/products/platform/atlas-vector-search,,"{""selfhost"":""Atlas is cloud-only; self-hosted MongoDB requires separate vector configuration""}"
Redis Vector,In-memory DB with vector search,1,0,0,1,1,1,1,1,1,1,1,0,0,1,1,0,"Python, JS, Java, Go, C#",1,"Linux, macOS, Windows",https://redis.io/docs/latest/develop/get-started/vector-database/,https://github.com/redis/redis,"{""ram"":""All data lives in RAM; disk persistence must be explicitly configured via AOF or RDB — not enabled by default"",""persistence"":""Persistence via AOF or RDB snapshots; must be explicitly enabled in redis.conf — off by default""}"
Neo4j,Native graph database platform,1,1,0,1,0,1,1,0,0,1,1,0,1,1,1,1,"Python, Java, JS, Go, .NET",1,"Linux, macOS, Windows",https://neo4j.com,https://github.com/neo4j/neo4j,
Memgraph,Real-time in-memory graph platform,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,"Python, JS, C++, Rust, Go",1,"Linux, macOS (Docker), Windows (Docker)",https://memgraph.com,https://github.com/memgraph/memgraph,"{""embeddable"":""In-memory server; not embeddable in the SQLite sense — requires a server process"",""persistence"":""Persists via periodic snapshots and WAL; primarily in-memory — recent in-flight writes may be lost on unexpected crash""}"
TigerGraph,Scalable graph analytics platform,1,1,0,1,0,1,0,0,0,1,1,0,1,1,1,0,"Python, Java, REST",0,"Linux, Cloud",https://tigergraph.com,,
Amazon Neptune,Managed graph database service,1,1,0,0,0,0,0,1,0,1,1,0,1,0,0,0,"Python, Java, JS, Go",0,AWS Cloud only,https://aws.amazon.com/neptune/,,
FalkorDB,Graph DB with vector search for AI,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,"Python, JS, Java, Go, Rust",1,"Linux, macOS, Windows",https://falkordb.com,https://github.com/FalkorDB/FalkorDB,"{""ram"":""Built on Redis; data is RAM-first with optional AOF/RDB persistence"",""persistence"":""Relies on Redis AOF/RDB persistence; must be explicitly enabled in Redis config — not on by default""}"
JanusGraph,"Distributed, open-source graph DB",0,1,1,1,0,1,0,0,0,1,1,0,1,0,0,0,"Java, Python, Gremlin",0,"Linux, macOS, Windows",https://janusgraph.org,https://github.com/JanusGraph/janusgraph,"{""docker"":""Official image requires an external storage backend (Cassandra, HBase, or BerkeleyDB) — additional services needed alongside it""}"
OrientDB,Multi-model DB (graph + document),0,1,1,1,1,1,1,1,0,1,1,1,1,0,0,0,"Java, Python, JS, SQL-like",0,"Linux, macOS, Windows",https://orientdb.org,https://github.com/orientechnologies/orientdb,
ArcadeDB,Multi-model DB inspired by OrientDB,0,1,1,1,1,1,1,1,0,1,1,1,1,0,0,1,"Java, Python, JS, HTTP",0,"Linux, macOS, Windows",https://arcadedb.com,https://github.com/ArcadeData/arcadedb,
ArangoDB,"Multi-model: graph, document, key-value",1,1,1,1,1,1,1,1,0,1,1,0,1,1,1,0,"Python, JS, Java, Go, PHP",1,"Linux, macOS, Windows",https://arangodb.com,https://github.com/arangodb/arangodb,"{""oss"":""Licensed under BSL 1.1 from v3.11+ — not OSI-approved open source; converts to Apache 2.0 after 4 years""}"
PG + pgvector + AGE,Postgres with graph + vector extensions,1,1,1,1,1,1,1,1,0,1,1,0,1,1,1,1,All Postgres clients,1,"Linux, macOS, Windows",https://github.com/apache/age,https://github.com/apache/age,"{""cypher"":""Cypher support via Apache AGE — implementation is partial; not all Cypher clauses or functions are supported""}"
CozoDB,"Embeddable, relational-graph-vector DB",1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,"Python, JS, Java, Rust",1,"Linux, macOS, Windows",https://cozodb.org,https://github.com/cozodb/cozo,"{""embeddable"":""Backend is configurable: in-memory, SQLite, or RocksDB"",""persistence"":""Depends on backend; SQLite and RocksDB backends are durable""}"
Vespa,Enterprise search + vector + analytics,1,0,1,1,0,1,1,0,0,1,1,0,0,1,1,0,"Java, Python, Rust, JS",1,"Linux, macOS (Docker)",https://vespa.ai,https://github.com/vespa-engine/vespa,
SurrealDB,"Multi-model: graph, doc, vector, SQL",1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,"Python, JS, Rust, Go, .NET, Java",1,"Linux, macOS, Windows",https://surrealdb.com,https://github.com/surrealdb/surrealdb,"{""embeddable"":""Embedded mode available via the embedded feature flag in Rust/Python""}"`;
