window.DB_CSV_DATA = `name,tagline,released,active,vector,graph,oss,selfhost,lightweight,docker,single,lowops,ram,persistence,server,embeddable,traversal,hybrid,rag,cypher,lc,langs,compat,url,src,notes
Qdrant,High-perf vector search engine,2020-05,1,1,0,1,1,1,1,1,1,0,1,1,0,0,1,1,0,1,"Python, Go, JS, Rust","Linux, macOS, Windows",https://qdrant.tech,https://github.com/qdrant/qdrant,
Chroma,AI-native open-source embedding DB,2023-02,1,1,0,1,1,1,1,1,1,0,1,1,1,0,1,1,0,1,"Python, JS/TS","Linux, macOS, Windows",https://trychroma.com,https://github.com/chroma-core/chroma,"{""persistence"":""Default in-memory mode has no persistence; use PersistentClient for durability""}"
Weaviate,AI-native vector database,2019-09,1,1,0,1,1,0,1,1,0,0,1,1,0,0,1,1,0,1,"Python, Go, JS, Java","Linux, macOS, Windows",https://weaviate.io,https://github.com/weaviate/weaviate,"{""oss"":""Uses Business Source License (BSL 1.1) from v1.25+ — not OSI-approved; converts to Apache 2.0 after 4 years""}"
Milvus,Cloud-native vector DB for scale,2019-10,1,1,0,1,1,0,1,1,0,0,1,1,0,0,1,1,0,1,"Python, Java, Go, JS","Linux, macOS, Windows",https://milvus.io,https://github.com/milvus-io/milvus,"{""single"":""Milvus Lite and standalone mode run on one machine; large production deployments often use distributed Milvus""}"
Pinecone,Fully managed vector database,2021-01,1,1,0,0,0,1,0,0,1,0,1,1,0,0,1,1,0,1,"Python, JS, Go, Java",Cloud (SaaS),https://pinecone.io,,
LanceDB,Serverless vector DB for AI apps,2023-05,1,1,0,1,1,1,1,1,1,0,1,1,1,0,1,1,0,1,"Python, JS/TS, Rust","Linux, macOS, Windows",https://lancedb.com,https://github.com/lancedb/lancedb,
pgvector,Vector similarity search for Postgres,2018-10,1,1,0,1,1,1,1,1,1,0,1,1,0,0,1,1,0,1,All Postgres clients,"Linux, macOS, Windows",https://github.com/pgvector/pgvector,https://github.com/pgvector/pgvector,
pgvectorscale,High-perf vector search on Postgres,2024-03,1,1,0,1,1,1,1,1,1,0,1,1,0,0,1,1,0,1,All Postgres clients,"Linux, macOS",https://github.com/timescale/pgvectorscale,https://github.com/timescale/pgvectorscale,
FAISS,Efficient similarity search library (Meta),2017-03,1,1,0,1,1,1,1,1,1,0,0,0,1,0,0,0,0,1,"Python, C++","Linux, macOS, Windows",https://faiss.ai,https://github.com/facebookresearch/faiss,"{""persistence"":""No built-in persistence; caller must manually save/load index files"",""server"":""Library only — no server mode; must be wrapped by the application"",""embeddable"":""In-process library with no storage engine; caller is fully responsible for saving and loading index files""}"
Elasticsearch,Distributed search & analytics engine,2010-02,1,1,0,0,1,0,1,1,0,0,1,1,0,0,1,1,0,1,"Python, Java, JS, Go, Ruby","Linux, macOS, Windows",https://elastic.co,https://github.com/elastic/elasticsearch,"{""selfhost"":""Server is under Elastic License v2 / SSPL (not OSI-approved); client libraries and some components differ""}"
MongoDB Atlas Vector,Document DB with vector search,2023-06,1,1,0,0,0,0,0,0,1,0,1,1,0,0,1,1,0,1,"Python, JS, Java, Go, C#",Cloud (SaaS),https://www.mongodb.com/products/platform/atlas-vector-search,,"{""selfhost"":""Atlas is cloud-only; self-hosted MongoDB requires separate vector configuration""}"
Redis Vector,In-memory DB with vector search,2009-04,1,1,0,0,1,1,1,1,1,1,1,1,0,0,1,1,0,1,"Python, JS, Java, Go, C#","Linux, macOS, Windows",https://redis.io/docs/latest/develop/get-started/vector-database/,https://github.com/redis/redis,"{""ram"":""All data lives in RAM; disk persistence must be explicitly configured via AOF or RDB — not enabled by default"",""persistence"":""Persistence via AOF or RDB snapshots; must be explicitly enabled in redis.conf — off by default"",""selfhost"":""Redis Server 7.4+ from Redis Ltd is RSALv2 / SSPL — not OSI-approved; earlier BSD-era releases differ""}"
Neo4j,Native graph database platform,2007-02,1,1,1,1,1,0,1,1,0,0,1,1,0,1,1,1,1,1,"Python, Java, JS, Go, .NET","Linux, macOS, Windows",https://neo4j.com,https://github.com/neo4j/neo4j,"{""oss"":""Community Edition is GPLv3 (OSI-approved); Enterprise Edition is commercial — open-core model""}"
Memgraph,Real-time in-memory graph platform,2016-06,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,"Python, JS, C++, Rust, Go","Linux, macOS (Docker), Windows (Docker)",https://memgraph.com,https://github.com/memgraph/memgraph,"{""persistence"":""Persists via periodic snapshots and WAL; primarily in-memory — recent in-flight writes may be lost on unexpected crash"",""hybrid"":""Vector similarity plus text predicates; combined ranking differs from dedicated BM25+vector hybrid engines""}"
TigerGraph,Scalable graph analytics platform,2016-09,1,1,1,0,1,0,1,0,0,0,1,1,0,1,1,1,0,1,"Python, Java, REST","Linux, Cloud",https://tigergraph.com,,"{""lc"":""LangChain includes a TigerGraph option in its community tools. LlamaIndex does not ship a simple TigerGraph plug-in - expect more do-it-yourself wiring.""}"
Amazon Neptune,Managed graph database service,2018-05,1,1,1,0,0,0,0,0,1,0,1,1,0,1,0,1,0,1,"Python, Java, JS, Go",AWS Cloud only,https://aws.amazon.com/neptune/,,"{""lc"":""Both LangChain and LlamaIndex can talk to Neptune, but you add Amazon-specific helpers and follow setup guides - extra install steps, not one-click defaults.""}"
FalkorDB,Graph DB with vector search for AI,2023-10,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,"Python, JS, Java, Go, Rust","Linux, macOS, Windows",https://falkordb.com,https://github.com/FalkorDB/FalkorDB,"{""ram"":""Built on Redis; data is RAM-first with optional AOF/RDB persistence"",""persistence"":""Relies on Redis AOF/RDB persistence; must be explicitly enabled in Redis config — not on by default""}"
JanusGraph,"Distributed, open-source graph DB",2017-01,1,0,1,1,1,0,1,0,0,0,1,1,0,1,0,0,0,1,"Java, Python, Gremlin","Linux, macOS, Windows",https://janusgraph.org,https://github.com/JanusGraph/janusgraph,"{""docker"":""Official image requires an external storage backend (Cassandra, HBase, or BerkeleyDB) — additional services needed alongside it"",""lc"":""LangChain reaches JanusGraph through a general Gremlin-style hook; connection details can be fiddly. LlamaIndex has no dedicated JanusGraph shortcut - plan for mostly manual glue code.""}"
OrientDB,Multi-model DB (graph + document),2011-03,1,0,1,1,1,1,1,1,1,0,1,1,1,1,0,0,0,0,"Java, Python, JS, SQL-like","Linux, macOS, Windows",https://orientdb.org,https://github.com/orientechnologies/orientdb,
ArcadeDB,Multi-model DB inspired by OrientDB,2021-03,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,"Java, Python, JS, HTTP","Linux, macOS, Windows",https://arcadedb.com,https://github.com/ArcadeData/arcadedb,"{""vector"":""Native JVector-based vector indexes (e.g. HNSW); general-purpose multi-model DB rather than a vector-only product"",""hybrid"":""Full-text (Lucene) plus vector indexes; dense+sparse tuning differs from search-first engines like Elasticsearch""}"
ArangoDB,"Multi-model: graph, document, key-value",2012-10,1,1,1,1,1,1,1,1,1,0,1,1,0,1,1,1,0,1,"Python, JS, Java, Go, PHP","Linux, macOS, Windows",https://arangodb.com,https://github.com/arangodb/arangodb,"{""oss"":""Licensed under BSL 1.1 from v3.11+ — not OSI-approved open source; converts to Apache 2.0 after 4 years""}"
PG + pgvector + AGE,Postgres with graph + vector extensions,2020-04,1,1,1,1,1,1,1,1,1,0,1,1,0,1,1,1,1,1,All Postgres clients,"Linux, macOS, Windows",https://github.com/apache/age,https://github.com/apache/age,"{""cypher"":""Cypher support via Apache AGE — implementation is partial; not all Cypher clauses or functions are supported""}"
CozoDB,"Embeddable, relational-graph-vector DB",2022-11,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,1,"Python, JS, Java, Rust","Linux, macOS, Windows",https://cozodb.org,https://github.com/cozodb/cozo,"{""embeddable"":""Backend is configurable: in-memory, SQLite, or RocksDB"",""persistence"":""Depends on backend; SQLite and RocksDB backends are durable"",""active"":""Last public commit on GitHub default branch: 2024-12-04 — over six months before this table was checked (2026-05-04); no newer commits visible — verify maintainer intent before adopting.""}"
Kuzu,Embeddable graph DB with Cypher vector and full-text,2022-11,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,"Python, Rust, Java, Node, C++","Linux, macOS, Windows",https://kuzudb.com,https://github.com/kuzudb/kuzu,"{""vector"":""Graph-first product; similarity search uses a native disk-backed vector index (HNSW-style extension), not a vector-only engine"",""hybrid"":""Full-text (FTS extension) and vector indexes exist; tuning and ranking differ from dedicated hybrid retrieval stacks"",""server"":""Network access is via the optional official Docker image kuzudb/api-server (HTTP API around the embedded engine), not a first-class long-lived database daemon in the core product"",""active"":""GitHub repo kuzudb/kuzu is archived (read-only); last push 2025-10-10. Status is off for new OSS-led adoption — confirm current vendor/product direction outside GitHub.""}"
Vespa,Enterprise search + vector + analytics,2017-09,1,1,0,1,1,0,1,1,0,0,1,1,0,0,1,1,0,1,"Java, Python, Rust, JS","Linux, macOS (Docker)",https://vespa.ai,https://github.com/vespa-engine/vespa,
SurrealDB,"Multi-model: graph, doc, vector, SQL",2021-09,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,1,"Python, JS, Rust, Go, .NET, Java","Linux, macOS, Windows",https://surrealdb.com,https://github.com/surrealdb/surrealdb,"{""embeddable"":""Embedded mode available via the embedded feature flag in Rust/Python"",""persistence"":""Default in-memory start (e.g. surreal start mem) is ephemeral; use rocksdb://, surrealkv://, or other disk backends for durable storage across restarts.""}"`;