window.DB_CSV_DATA = `name,tagline,ideal,released,active,vector,graph,oss,selfhost,lightweight,docker,single,lowops,ram,persistence,server,embeddable,traversal,hybrid,rag,cypher,lc,langs,implang,compat,url,src,ghstars,notes
Amazon Neptune,Managed graph database service,Managed Gremlin / SPARQL graph on AWS without operating your own graph cluster,2018-05,1,1,1,0,0,0,0,0,1,0,1,1,0,1,0,1,0,1,"Python, Java, JS, Go",Proprietary (undisclosed),AWS Cloud only,https://aws.amazon.com/neptune/,,,"{""lc"":""Both LangChain and LlamaIndex can talk to Neptune, but you add Amazon-specific helpers and follow setup guides - extra install steps, not one-click defaults.""}"
ArangoDB,"Multi-model: graph, document, key-value","One DB for documents, graph, key-value, and vectors with flexible deployment",2012-10,1,1,1,1,1,1,1,1,1,0,1,1,0,1,1,1,0,1,"Python, JS, Java, Go, PHP",C++,"Linux, macOS, Windows",https://arangodb.com,https://github.com/arangodb/arangodb,14155,"{""oss"":""Licensed under BSL 1.1 from v3.11+ — not OSI-approved open source; converts to Apache 2.0 after 4 years""}"
ArcadeDB,Multi-model DB inspired by OrientDB,"Java teams wanting Lucene-backed multi-model graph, document, and vector",2021-03,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,"Java, Python, JS, HTTP",Java,"Linux, macOS, Windows",https://arcadedb.com,https://github.com/ArcadeData/arcadedb,845,"{""vector"":""Native JVector-based vector indexes (e.g. HNSW); general-purpose multi-model DB rather than a vector-only product"",""hybrid"":""Full-text (Lucene) plus vector indexes; dense+sparse tuning differs from search-first engines like Elasticsearch""}"
Chroma,AI-native open-source embedding DB,RAG and embedding storage for fast Python or JS prototypes and small services,2023-02,1,1,0,1,1,1,1,1,1,0,1,1,1,0,1,1,0,1,"Python, JS/TS",Rust / Python,"Linux, macOS, Windows",https://trychroma.com,https://github.com/chroma-core/chroma,27836,"{""persistence"":""Default in-memory mode has no persistence; use PersistentClient for durability""}"
CogDB,Embedded graph + vectors for Python (Torque API),Embedded Python graph plus vectors without a separate database server,2017-03,1,1,1,1,1,1,0,1,1,0,1,1,1,1,0,1,0,0,Python,Python,"Linux, macOS, Windows, Web (Pyodide)",https://cogdb.io,https://github.com/arun1729/cog,357,"{""docker"":""No official Docker image documented as a primary install path — ship via pip inside your own image"",""hybrid"":""Graph traversal plus embedding similarity; not a dedicated vector+sparse/keyword hybrid engine"",""server"":""Optional HTTP via Graph.serve() / remote Graph.connect — embedded-first, not a traditional always-on DB server product"",""lc"":""No first-class LangChain or LlamaIndex package in-tree — integrate as a Python library""}"
CozoDB,"Embeddable, relational-graph-vector DB",In-process relational-graph-vector workloads with Datalog-style queries,2022-11,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,1,"Python, JS, Java, Rust",Rust,"Linux, macOS, Windows",https://cozodb.org,https://github.com/cozodb/cozo,3984,"{""embeddable"":""Backend is configurable: in-memory, SQLite, or RocksDB"",""persistence"":""Depends on backend; SQLite and RocksDB backends are durable"",""active"":""Last public commit on GitHub default branch: 2024-12-04 — over six months before this table was checked (2026-05-04); no newer commits visible — verify maintainer intent before adopting.""}"
Elasticsearch,Distributed search & analytics engine,Log and text search plus hybrid vector-keyword at ELK-style scale,2010-02,1,1,0,0,1,0,1,1,0,0,1,1,0,0,1,1,0,1,"Python, Java, JS, Go, Ruby",Java,"Linux, macOS, Windows",https://elastic.co,https://github.com/elastic/elasticsearch,76646,"{""selfhost"":""Server is under Elastic License v2 / SSPL (not OSI-approved); client libraries and some components differ""}"
FAISS,Efficient similarity search library (Meta),Maximum-throughput ANN when you control persistence and serving yourself,2017-03,1,1,0,1,1,1,1,1,1,0,0,0,1,0,0,0,0,1,"Python, C++",C++,"Linux, macOS, Windows",https://faiss.ai,https://github.com/facebookresearch/faiss,39947,"{""persistence"":""No built-in persistence; caller must manually save/load index files"",""server"":""Library only — no server mode; must be wrapped by the application"",""embeddable"":""In-process library with no storage engine; caller is fully responsible for saving and loading index files""}"
FalkorDB,Graph DB with vector search for AI,Redis-speed graph and vector for low-latency real-time product features,2023-10,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,"Python, JS, Java, Go, Rust",C,"Linux, macOS, Windows",https://falkordb.com,https://github.com/FalkorDB/FalkorDB,4338,"{""ram"":""Built on Redis; data is RAM-first with optional AOF/RDB persistence"",""persistence"":""Relies on Redis AOF/RDB persistence; must be explicitly enabled in Redis config — not on by default""}"
JanusGraph,"Distributed, open-source graph DB","Very large Gremlin graphs on Cassandra, HBase, or similar backends",2017-01,1,0,1,1,1,0,1,0,0,0,1,1,0,1,0,0,0,1,"Java, Python, Gremlin",Java,"Linux, macOS, Windows",https://janusgraph.org,https://github.com/JanusGraph/janusgraph,5771,"{""docker"":""Official image requires an external storage backend (Cassandra, HBase, or BerkeleyDB) — additional services needed alongside it"",""lc"":""LangChain reaches JanusGraph through a general Gremlin-style hook; connection details can be fiddly. LlamaIndex has no dedicated JanusGraph shortcut - plan for mostly manual glue code.""}"
Kuzu,Embeddable graph DB with Cypher vector and full-text,"Embedded Cypher graph, vector search, and full-text in one library",2022-11,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,"Python, Rust, Java, Node, C++",C++,"Linux, macOS, Windows",https://kuzudb.com,https://github.com/kuzudb/kuzu,3892,"{""vector"":""Graph-first product; similarity search uses a native disk-backed vector index (HNSW-style extension), not a vector-only engine"",""hybrid"":""Full-text (FTS extension) and vector indexes exist; tuning and ranking differ from dedicated hybrid retrieval stacks"",""server"":""Network access is via the optional official Docker image kuzudb/api-server (HTTP API around the embedded engine), not a first-class long-lived database daemon in the core product"",""active"":""GitHub repo kuzudb/kuzu is archived (read-only); last push 2025-10-10. Status is off for new OSS-led adoption — confirm current vendor/product direction outside GitHub.""}"
LanceDB,Serverless vector DB for AI apps,Columnar vectors on object storage and lake-style AI data pipelines,2023-05,1,1,0,1,1,1,1,1,1,0,1,1,1,0,1,1,0,1,"Python, JS/TS, Rust",Rust,"Linux, macOS, Windows",https://lancedb.com,https://github.com/lancedb/lancedb,10205,
Memgraph,Real-time in-memory graph platform,"Streaming, real-time graph analytics with an in-memory-first design",2016-06,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,"Python, JS, C++, Rust, Go",C++,"Linux, macOS (Docker), Windows (Docker)",https://memgraph.com,https://github.com/memgraph/memgraph,3979,"{""persistence"":""Persists via periodic snapshots and WAL; primarily in-memory — recent in-flight writes may be lost on unexpected crash"",""hybrid"":""Vector similarity plus text predicates; combined ranking differs from dedicated BM25+vector hybrid engines""}"
Milvus,Cloud-native vector DB for scale,Billion-scale vector search in Kubernetes-oriented production stacks,2019-10,1,1,0,1,1,0,1,1,0,0,1,1,0,0,1,1,0,1,"Python, Java, Go, JS",Go / C++,"Linux, macOS, Windows",https://milvus.io,https://github.com/milvus-io/milvus,44143,"{""single"":""Milvus Lite and standalone mode run on one machine; large production deployments often use distributed Milvus""}"
MongoDB Atlas Vector,Document DB with vector search,Document model plus vector search in managed MongoDB Atlas,2023-06,1,1,0,0,0,0,0,0,1,0,1,1,0,0,1,1,0,1,"Python, JS, Java, Go, C#",C++,Cloud (SaaS),https://www.mongodb.com/products/platform/atlas-vector-search,,,"{""selfhost"":""Atlas is cloud-only; self-hosted MongoDB requires separate vector configuration""}"
Neo4j,Native graph database platform,General property-graph and Cypher workloads from apps to knowledge graphs,2007-02,1,1,1,1,1,0,1,1,0,0,1,1,0,1,1,1,1,1,"Python, Java, JS, Go, .NET",Java,"Linux, macOS, Windows",https://neo4j.com,https://github.com/neo4j/neo4j,16429,"{""oss"":""Community Edition is GPLv3 (OSI-approved); Enterprise Edition is commercial — open-core model""}"
OrientDB,Multi-model DB (graph + document),Legacy Java stacks that mix graph and document in one multi-model DB,2011-03,1,0,1,1,1,1,1,1,1,0,1,1,1,1,0,0,0,0,"Java, Python, JS, SQL-like",Java,"Linux, macOS, Windows",https://orientdb.org,https://github.com/orientechnologies/orientdb,4953,
PG + pgvector + AGE,Postgres with graph + vector extensions,SQL teams combining Postgres vectors with Cypher via Apache AGE,2020-04,1,1,1,1,1,1,1,1,1,0,1,1,0,1,1,1,1,1,All Postgres clients,C (Postgres core + pgvector & AGE extensions),"Linux, macOS, Windows",https://github.com/apache/age,https://github.com/apache/age,4483,"{""cypher"":""Cypher support via Apache AGE — implementation is partial; not all Cypher clauses or functions are supported""}"
pgvector,Vector similarity search for Postgres,Adding vector similarity to existing Postgres without a new datastore,2018-10,1,1,0,1,1,1,1,1,1,0,1,1,0,0,1,1,0,1,All Postgres clients,C,"Linux, macOS, Windows",https://github.com/pgvector/pgvector,https://github.com/pgvector/pgvector,21131,
pgvectorscale,High-perf vector search on Postgres,DiskANN-style indexes on Postgres for large vector workloads,2024-03,1,1,0,1,1,1,1,1,1,0,1,1,0,0,1,1,0,1,All Postgres clients,Rust,"Linux, macOS",https://github.com/timescale/pgvectorscale,https://github.com/timescale/pgvectorscale,2998,
Pinecone,Fully managed vector database,Fully managed vectors when you want zero infrastructure for ANN serving,2021-01,1,1,0,0,0,1,0,0,1,0,1,1,0,0,1,1,0,1,"Python, JS, Go, Java",Proprietary (undisclosed),Cloud (SaaS),https://pinecone.io,,,
Qdrant,High-perf vector search engine,"Self-hosted or cloud vector APIs with payloads, filters, and tuning",2020-05,1,1,0,1,1,1,1,1,1,0,1,1,0,0,1,1,0,1,"Python, Go, JS, Rust",Rust,"Linux, macOS, Windows",https://qdrant.tech,https://github.com/qdrant/qdrant,31081,
Redis Vector,In-memory DB with vector search,Vector similarity inside Redis-centric low-latency architectures,2009-04,1,1,0,0,1,1,1,1,1,1,1,1,0,0,1,1,0,1,"Python, JS, Java, Go, C#",C,"Linux, macOS, Windows",https://redis.io/docs/latest/develop/get-started/vector-database/,https://github.com/redis/redis,74173,"{""ram"":""All data lives in RAM; disk persistence must be explicitly configured via AOF or RDB — not enabled by default"",""persistence"":""Persistence via AOF or RDB snapshots; must be explicitly enabled in redis.conf — off by default"",""selfhost"":""Redis Server 7.4+ from Redis Ltd is RSALv2 / SSPL — not OSI-approved; earlier BSD-era releases differ""}"
RyuGraph,"Embedded graph DB (Kuzu fork): Cypher, vector, full-text",Continuing embedded Cypher-graph-vector after Kuzu upstream archival,2025-10,1,1,1,1,1,1,0,1,1,0,1,1,1,1,1,1,1,1,"Python, Rust, Java, Node, C++, WASM",C++,"Linux, macOS, Windows, Web (WASM)",https://www.ryugraph.io/,https://github.com/predictable-labs/ryugraph,136,"{""graph"":""Continuation fork of Kuzu after upstream archival (Oct 2025); maintained by Predictable Labs under MIT — treat Kuzu↔RyuGraph migration as a separate evaluation"",""vector"":""Graph-first; native disk-backed vector indexes (Kuzu lineage), not a vector-only engine"",""hybrid"":""Full-text and vector indexes; ranking and tuning differ from dedicated hybrid retrieval stacks"",""server"":""Optional HTTP API around the embedded engine may be offered via containers or bindings (see docs); not a traditional always-on database daemon in core"",""docker"":""No first-class database-server Docker image called out in the README; optional ghcr.io/predictable-labs/extension-repo image hosts extensions for some older install flows — v0.11.3+ ships common extensions pre-installed"",""lowops"":""Extension install historically could require a local extension server; current releases reduce that for common extensions — read release notes before assuming zero extra services""}"
SurrealDB,"Multi-model: graph, doc, vector, SQL","Modern multi-model graph, documents, vectors, and SQL in Rust",2021-09,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,1,"Python, JS, Rust, Go, .NET, Java",Rust,"Linux, macOS, Windows",https://surrealdb.com,https://github.com/surrealdb/surrealdb,32036,"{""embeddable"":""Embedded mode available via the embedded feature flag in Rust/Python"",""persistence"":""Default in-memory start (e.g. surreal start mem) is ephemeral; use rocksdb://, surrealkv://, or other disk backends for durable storage across restarts.""}"
TigerGraph,Scalable graph analytics platform,Massively parallel graph analytics and large-scale graph data science,2016-09,1,1,1,0,1,0,1,0,0,0,1,1,0,1,1,1,0,1,"Python, Java, REST",C++,"Linux, Cloud",https://tigergraph.com,,,"{""lc"":""LangChain includes a TigerGraph option in its community tools. LlamaIndex does not ship a simple TigerGraph plug-in - expect more do-it-yourself wiring.""}"
Vespa,Enterprise search + vector + analytics,"Big Internet-style serving: ranking, vectors, and structured data together",2017-09,1,1,0,1,1,0,1,1,0,0,1,1,0,0,1,1,0,1,"Java, Python, Rust, JS",Java / C++,"Linux, macOS (Docker)",https://vespa.ai,https://github.com/vespa-engine/vespa,6906,
Weaviate,AI-native vector database,Modular vector DB with schema and GraphQL for AI retrieval products,2019-09,1,1,0,1,1,0,1,1,0,0,1,1,0,0,1,1,0,1,"Python, Go, JS, Java",Go,"Linux, macOS, Windows",https://weaviate.io,https://github.com/weaviate/weaviate,16139,"{""oss"":""Uses Business Source License (BSL 1.1) from v1.25+ — not OSI-approved; converts to Apache 2.0 after 4 years""}"`;